### ISSUE TITLE
Lists price / sale price

### ISSUE THREAD

**Issue by ryanspooner** [DouglasCAyers/sfdc-change-opportunity-pricebook-flow#1]
Hey this is a great solution! Quick question
When you change the pricebook on the opp it changes the list price to the new pricebook but sales price remains the same. Is there a way to modify this to change the sales price to the list price as well?

Thanks,
Ryan

**Comment by douglascayers** [comment]
Hi @ryanspooner,

Thanks for the kind feedback. This should be doable, let me take a look at the code to see where to add in the option.

Doug

**Comment by douglascayers** [comment]
@ryanspooner I've updated the flow with a new option `overwriteUnitPrice`.

When overwriteUnitPrice is true then prices from new price book are used.
When overwriteUnitPrice is false then prices are kept the same, unchanged.

The default is *false*, so you must update the flow to accommodate overwriting the prices if desired. You might want to update the initial screen element to prompt user if they want to overwrite the prices or not. I did not go that far with this update, just provide the ability to do so.

![capture](https://cloud.githubusercontent.com/assets/4142577/26030296/05378328-3815-11e7-928a-565f2019472a.PNG)

Thanks!

**Comment by ryanspooner** [comment]
Thats awesome, thanks a lot! I'm gonna mess with it on Monday.
Thanks for getting back to me so soon, you are the man!

Thanks again,
Ryan

[image: RS Logo] <http://www.ryanspooner.com/>

Ryan Spooner
908.310.2080
ryan@ryanspooner.com
www.ryanspooner.com
